### ISSUE TITLE
metadata.name replaced by NameSuffixHash in plugin 

### ISSUE THREAD

**Issue by cyphermaster** [monopole/sopsencodedsecrets#1]
Hi, 
Tested locally with a gpg key instead of kms (SOPS_PGP_FP env to select it)

test:
[demosops.txt](https://github.com/monopole/sopsencodedsecrets/files/3329183/demosops.txt)

result:
```
apiVersion: v1
data:
  CAR: ZHltYXhpb24=
  ROCKET: c2F0dXJuLXY=
kind: Secret
metadata:
  name: -hmg9gtg9k6
  namespace: production
type: Opaque
```
Seems like the name was omitted

regards,
